# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20171022_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
